Application/Controllers/VendaController.cs
using Domain.Models;
using Domain.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace SistemaVenda.Controllers
{
    public class VendaController : Controller
    {
        private readonly IVendaService _vendaService;
        private readonly IProdutoService _produtoService;
        private readonly IClienteService _clienteService;
        public VendaController(IVendaService vendaService, IProdutoService produtoService, IClienteService clienteService)
        {
            _vendaService = vendaService;
            _produtoService = produtoService;
            _clienteService = clienteService;
        }

        public IActionResult Index()
        {
            return View(_vendaService.GetAll());
        }

        [HttpGet]
        public IActionResult Cadastro(int? Id)
        {
            if (!Id.HasValue)
            {
                var viewModel = new VendaViewModel();
                viewModel.ListaClientes = _clienteService.ListaClientes();
                viewModel.ListaProdutos = _produtoService.ListaProdutos();
                return View(viewModel);
            }

            return View(_vendaService.Get((int)Id));
        }

        [HttpPost]
        public IActionResult Cadastro(VendaViewModel entidade)
        {
            if (!ModelState.IsValid)
            {
                entidade.ListaClientes = _clienteService.ListaClientes();
                entidade.ListaProdutos = _produtoService.ListaProdutos();
                return View(entidade);
            }

            _vendaService.Insert(entidade);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Excluir(int Id)
        {
            _vendaService.Delete(Id);
            return RedirectToAction("Index");
        }

        [HttpGet("LerValorProduto/{CodigoProduto}")]
        public decimal? LerValorProduto(int CodigoProduto)
        {
            return _produtoService.Get(CodigoProduto).Valor;
        }

    }
}

Application/Views/Venda/Cadastro.cshtml
@model Domain.Models.VendaViewModel;

@{
    var disabled = (Model.Codigo == null) ? "disabled" : string.Empty;
}
<html>
<head>
    <title>Venda</title>
    <meta charset="utf-8" />
    <style>
    </style>
</head>
<body>

    <div class="The-title">
        <h2>Vendas</h2>
        <hr />
    </div>
    <form asp-controller="Venda" asp-action="Cadastro" method="post">
        <input type="hidden" asp-for="Codigo" value="@Model.Codigo" />
        <div class="form-group">
            <div class="col-4">
                <label>Data</label>

                @if (Model.Codigo != null)
                {
                    <input type="text" asp-for="Data" value="@Model.Data.Value.ToShortDateString()" class="form-control" disabled />
                }
                else
                {
                    <input type="date" asp-for="Data" value="@Model.Data" class="form-control" />
                    <span asp-validation-for="Data" class="text-danger"></span>
                }
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-4">
                <label>Cliente</label>
                <input type="hidden" asp-for="ListaClientes" value="@Model.ListaClientes" class="form-control" />
                <select asp-for="CodigoCliente" asp-items="@Model.ListaClientes" class="form-control" input-lg></select>
                <span asp-validation-for="CodigoCliente" class="text-danger"></span>
            </div>
        </div>
        <br />
        @if (Model.Codigo == null)
        {
            <div class="form-group">
                <div class="col-4">
                    <label>Produtos</label>
                    <select id="cboProduto" onchange="BuscarPreco()" asp-items="@Model.ListaProdutos" class="form-control" input-lg></select>
                </div>
            </div>
            <br />
            <div class="form-group">
                <div class="col-2">
                    <label> Preço Unitário</label>
                    <input id="textPrecoUnitario" type="number" class="form-control" disabled />


                </div>
                <div class="col-2">
                    <label> Quantidade</label>
                    <input id="Qtde" type="number" class="form-control" onchange="CalcularSubtTotal()" />

                </div>
                <div class="col-2">
                    <label>Sub Total</label>
                    <input id="textsubtotal" type="number" class="form-control" disabled />

                </div>
                <div class="col-2">
                    <br />
                    <button type="button" class="btn btn-info" onclick="AddProduto()">Adicionar</button>
                    <br />
                </div>
            </div>
        }
        <div class="form-group">
            <div class="col-12">
                <table class="table table-bordered">
                    <thead>
                        <tr style="background:#f6f6f6">
                            <td>Produto</td>
                            <td>Preço Unitario</td>
                            <td>Quantidade</td>
                            <td>ToTal</td>
                        </tr>
                    </thead>
                    <tbody id="gridprodutos">

                        @if (Model.Codigo != null)
                        {
                            foreach (var item in Model.vendas)
                            {
                                <tr>
                                    <td> @item.Descricao</td>
                                    <td> @(item.Valor / item.Quantidade)</td>
                                    <td> @item.Quantidade</td>
                                    <td> @item.Valor</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3">
                <label>Total da Venda</label>
                @if (Model.Codigo != null)
                {
                    <input id="textTotal" class="form-control"  type="text" value="@Model.vendas.Sum(x=> x.Valor)" disabled />
                }
                else
                {
                    <input id="textTotal" class="form-control" asp-for="Total" type="number" value="@Model.Total" disabled />
                    <span asp-validation-for="Total" class="text-danger"></span>
                }
            </div>
        </div>
        <input type="text" asp-for="JsonProdutos" id="textJsonProdutos" style="display:none;" />
        <br />
        <div class="col">
            <button type="button" class="btn btn-info" onclick="Novo()">
                Novo
            </button>
            <button type="submit" class="btn btn-success">
                Gravar
            </button>
            <button type="button" class="btn btn-warning" onclick="Listagem()">
                listagem
            </button>
            <button type="button" class="btn btn-danger" onclick="Excluir(@Model.Codigo)" @disabled>
                Excluir
            </button>
        </div>
    </form>

    <script>
        var items = new Object;
        items.Produtos = new Array;
        var gridprodutos = document.getElementById("grid-produtos");
        function AddProduto() {
            var codigoproduto = document.getElementById("cboProduto").value;
            var qtde = document.getElementById("Qtde").value;
            var ValorUnitario = document.getElementById("textPrecoUnitario").value;
            var subtotal = document.getElementById("textsubtotal").value;
            items.Produtos.push({
                "codigoproduto": codigoproduto,
                "Quantidade": qtde,
                "Total": subtotal,
                "Valorunitario": ValorUnitario
            });
            document.getElementById("textJsonProdutos").value = JSON.stringify(items.Produtos);

            var linhagrid =
                "<tr>" +
                "<td>" + codigoproduto + "</td>" +
                "<td>" + ValorUnitario + "</td>" +
                "<td>" + qtde + "</td>" +
                "<td>" + subtotal + "</td>" +
                "</tr>";

            document.getElementById("gridprodutos").innerHTML += linhagrid;

            var total = Number(document.getElementById("textTotal").value.toString().replace(",", ".")) + Number(subtotal);

            document.getElementById("textTotal").value = total;
            document.getElementById("cboProduto").value = "";
            document.getElementById("Qtde").value = "";
            document.getElementById("textPrecoUnitario").value = "";
            document.getElementById("textsubtotal").selectedIndex = -1;
        }
        function BuscarPreco() {
            var CodigoProduto = document.getElementById("cboProduto");
            url = `/LerValorProduto/${CodigoProduto.value}`;
            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function () {
                if (xhr.readyState == XMLHttpRequest.DONE) {

                    document.getElementById("textPrecoUnitario").value = xhr.responseText;
                }
            }
            xhr.open('GET', url, false);
            xhr.send(null);
        }
        function CalcularSubtTotal() {
            var PrecoUnitario = document.getElementById("textPrecoUnitario").value;
            var Subtotal = PrecoUnitario * document.getElementById("Qtde").value;

            document.getElementById("textsubtotal").value = Subtotal;
        }
        function Novo() {
            Request("Cadastro");
        }
        function Listagem() {
            Request("");
        }
        function Excluir(Codigo) {
            Request("Excluir\\" + Codigo);
        }
        function Request(request) {
            window.location = window.origin + "\\Venda\\" + request;
        }
    </script>
</body>
</html>

Application/Views/Venda/Index.cshtml
@model List<Domain.Models.VendaViewModel>;
<html>
<head>

</head>
<body>
    <div class="The-title">
        <h2>Vendas</h2>
        <hr />
    </div>
    <div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th> Codigo</th>
                    <th> Data</th>
                    <th> Cliente</th>
                    <th> Total</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count() > 0)
                {
                    @foreach (var item in Model)
                    {
                        <tr onclick="Editar(@item.Codigo)" style="cursor:pointer;">
                            <td> @item.Codigo</td>
                            <td> @Convert.ToDateTime(item.Data).ToShortDateString()</td>
                            <td> @(item.NomeCliente != null ? item.NomeCliente : "não cadastrado")</td>
                            <td> @item.Total</td>
                        </tr>
                    }
                }

            </tbody>
        </table>
        <br />
        <button type="button" class="btn-block btn-primary" onclick="Cadastro()">
            registrar venda
        </button>
    </div>
    <script>
        function Editar(Codigo) {
            window.location = window.origin + "\\Venda\\Cadastro\\" + Codigo;

        }
        function Cadastro() {
            window.location = window.origin + "\\Venda\\Cadastro";
        }
    </script>

</body>
</html>